import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Chapter II | Nevada County Natural Resources Report',
};

const html = `

      <h1><br>
      <span class="header1">Chapter II: Methods</span>
      </h1>
      <h2 id="c2-elevation-zones">
Nevada County Elevation Zones</h2>
      <p>Nevada County’s 100 watersheds were mapped according to a slightly modified version of the California Watershed Map (CALWATER 2.0). This map was distributed by the California Department of Fish and Game (DFG) and was dated March 9, 1998 for its boundary data content. The Science Team obtained this map coverage from the State of California Stephen P. Teale Data Center GIS Lab (Teale). Teale is under contract to the California Department of Water Resources (DWR) for this project; DFG is an in-kind cooperator.</p>
      <p>
<img src="/images/elevation.gif" style="max-width:170px" class="img-float-left">A draft Memorandum of Understanding (MOU) has been prepared for the purpose of promoting the use, management, and maintenance of a common watershed map of California. Signatories of the MOU include the following state and federal agencies with water resources, water quality, soils, forest, watershed, fish, and wildlife habitat responsibilities: DFG, DWR, California Department of Forestry and Fire Protection (CDF), State Water Resources Control Board (SWRCB), USDA Forest Service (USFS) Pacific Southwest Region (R5), USDA Natural Resources Conservation Service (NRCS), USDI Geologic Survey (USGS), USDI Bureau of Reclamation (USBR), USDI Bureau of Land Management (BLM), U.S. Environmental Protection Agency (USEPA) Region IX, and Teale.</p>
      <p>
CALWATER 2.0 lists 98 planning watersheds greater than 150 acres in Nevada County. Minor corrections of watershed boundaries, including the division of the unusually large “Wolf Ditch” watershed into three sub-basins, yielded the final 100 watersheds used by the Science Team to define natural watershed and vegetation boundaries.  For purposes of this report, data for each of the county’s 100 watersheds were summarized according to one of four elevation zones that were defined as: </p>
      <p>
<u>Zone 1:</u> Foothill Watersheds—dominated by Foothill Hardwood and Oak-Foothill Pine Woodlands and Annual Grasslands (see “Habitat Classification,” below);</p>
      <p>
<u>Zone 2:</u> Transitional Watersheds—dominated by large-patch ecosystems from both Foothill Watersheds and Westside Conifer Watersheds; </p>
      <p>
<u>Zone 3:</u> Westside Conifer Watersheds—dominated by Ponderosa Pine, Mixed-Conifer, Red Fir, Subalpine Forest, or Montane Chaparral; and, </p>
      <p>
<u>Zone 4:</u> Eastside Watersheds—dominated by Eastside Pine and/or Eastside Scrub, with some Red Fir and Mixed-Conifer Forest.</p>
      <p>
All of these zones overlap at their boundaries, and plant or animal species that are common in one zone may also occur in an adjacent zone. The final boundaries of the four elevation zones are shown in <a href="/tables-figures#f2">Figure 2-1</a>. The locations of the county’s 100 watersheds within the four zones are shown in <a href="/tables-figures#f2">Figures 2-2 to 2-4</a>. </p>
      <h3 id="c2-habitat-classification"><i>Habitat Classification</i> 
      </h3>
      <p>Several systems have been developed recently for classifying the diverse natural vegetation of California including the Holland system (Holland 1986), Sawyer and Keeler-Wolf system (Sawyer and Keeler-Wolf 1995), and the California Wildlife Habitat Relationships (CWHR) system (Mayer and Laudenslayer 1988, Zeiner et al. 1990).</p>
      <p>
<i>Large-Patch Ecosystems</i></p>
      <p>After careful reviews of these classification systems, the SAC selected the CWHR system as the primary method for describing the “large-patch” ecosystems of Nevada County.  Large-patch ecosystems were defined in this report as the county’s dominant vegetation types that could be mapped and field-verified at a watershed scale (i.e., continuous patches &gt; 10 acres in extent). The CWHR system provides a relatively simple and accurate method for classifying large patches of vegetation, and this system is widely used by professional foresters and wildlife biologists throughout California.  It is also the most easily understood of the published vegetation classification systems for use by decision-makers and the public.</p>
      <p>
The CWHR system was developed for use state-wide, so the SAC refined it to reflect more accurately the large-patch ecosystems present in Nevada County.  This revised, Nevada County Wildlife Habitat Relationships (NCWHR), system is similar to the CWHR system except that some related habitat categories were combined as one major type. For example, the CWHR “Bitterbrush” and “Sagebrush” cover types were combined in the NCWHR system as “Eastside Scrub.” The Eastside Scrub definition reflects that Bitterbrush and Sagebrush are ecologically similar and that they overlap over broad areas in Nevada County. </p>
      <p>
The NCWHR classification system recognizes 27 large-patch ecosystems in Nevada County that occur in one or several elevation zones (<a href="/tables-figures#t2">Table 2-1</a>). In addition to native vegetation types, NCWHR large-patch ecosystems included croplands, orchards, vineyards, and urban/suburban areas that are also recognized in the CWHR system.  A “cross-walk” comparing the NCWHR large- and small-patch ecosystems with the CWHR (Mayer and Laudenslayer 1988), Holland (1986), and Sawyer and Keeler-Wolf (1995) systems is provided in <a href="/tables-figures#t2">Table 2-2</a>.</p>
      <p><i>
Small-Patch Ecosystems</i></p>
      <p>Within a more general scheme of wildlife habitat classification, such as that found in CWHR system, professional botanists often use the Holland (1986) and Sawyer and Keeler-Wolf (1995) systems to characterize complex plant associations. Because they are more botanically comprehensive, the SAC used the Holland (1986) and the Sawyer and Keeler-Wolf (1995) systems to describe some “small-patch” ecosystems in Nevada County. </p>
      <p>
The SAC defined small-patch ecosystems as isolated or unique plant or soil communities. These include rare habitats with highly restricted ranges, that may have unusual qualities and rare species, and that are generally small in size (i.e., &lt; 10 acres per occurrence).  Small-patch ecosystems also include some disjunct occurrences of larger ecosystems that may be more common in other parts of the state but that are rare in the Sierra Nevada. The NCWHR system recognizes the following small-patch ecosystems in Nevada County: seeps, springs, and “fens” (bog-like habitats); locally scarce stands of late-successional conifer forests; McNab cypress, whitebark pine, knobcone pine, and leather oak chaparral; serpentine and gabbrodiorite soils; volcanic lava caps and mudflows, and caves and mineshafts (Table 2-1).</p>
      <h3 id="c2-plant-diversity">
<i>Plant Diversity</i></h3>
      <p>The Science Team compiled a list of the vascular plants of Nevada County from university and agency databases, published literature on the flora of Nevada County, consultations with agency personnel, the local chapter of the California Native Plant Society (CNPS), and other local botanists (Appendix I).  This list includes all plant species that are known to occur in the county, including introduced species and extremely rare species known from only a few isolated occurrences.  All species on this list were based on published sources on the flora of Nevada County, or they were supported by voucher specimens in the herbaria of universities and public agencies.</p>
      <p>
The largest collections of Nevada County plant specimens are contained in the following herbaria: University of California, Berkeley (UCB); the California Academy of Sciences; and the University of California, Davis (UCD).  These herbaria contain plant specimens that were collected in the mid- to late 1800’s by both plant collectors and early pioneers, such as John Fremont. Appendix I does not include species known to occur here only from generalized distributional information contained in regional or statewide floras. Data on the mosses and lichens of Nevada County are not yet available through any databases or published sources, but many specimens can be found in the herbaria of UCB and UCD.</p>
      <p>
The Science Team consulted the following published sources and electronic databases for information on documented occurrences of plant species in Nevada County: Ferns, Fern Allies and Seed Plants of Nevada County (True 1973); California Natural Diversity Database (CNDDB 2002a); Inventory of Rare and Endangered Plants of California (CNPS 2001); CalFlora Database (CalFlora 2002); Tahoe National Forest Sensitive Plant Handbook (USDA 2000); Plants of Nevada County (CNPS, Redbud Chapter 2000, unpublished); Plants of the Tahoe Basin (Graf 1999); Ecological Guide to Eastside Pine (USDA 1993); Ecological Guide to Mixed Conifer (USDA 1993); Status of Rare and Endemic Plants in the Sierra Nevada (Shevock 1996); as well as several reports prepared for projects in Nevada County (GANDA 2000 and 2002). The CalFlora Database was also used. CalFlora is a collaborative project that includes over 800,000 specimen records and other information from many contributors including UCB, USFS, U.S. Geological Survey, Harvard University, San Jose State University, UCD Information Center on the Environment (ICE), USDA National Plant Data Center, and the Santa Barbara Botanic Garden Herbarium.</p>
      <h3 id="c2-redyellow-plants">
<i>Redlist and Yellowlist Plants</i></h3>
      <p>For this project, Redlist plants were defined as those species and subspecies that are listed as Threatened, Endangered, or Candidates on the state and/or federal endangered species lists.  Yellowlist plants include all other species and subspecies that are included on lists of sensitive or special concern taxa that are maintained by federal agencies, e.g., U.S. Fish and Wildlife Service (USFWS), USDI Bureau of Land Management (BLM) , state agencies (e.g., DFG, CDF), and those taxa that are considered rare, threatened, or endangered by the California Native Plant Society (CNPS 2001). </p>
      <p>
A list of Redlist and Yellowlist plants (including vascular plants, bryophytes [i.e., mosses], and lichens) with known or potential occurrence in Nevada County was compiled after conducting a literature review of their regional status and distribution (Appendix II).  The Tahoe National Forest was an important source for information (USDA 2000) on Redlist and Yellowlist plants, vegetation communities, and noxious weeds. Other primary information sources for compiling this list include the following electronic databases: CNDDB (2002a), California Department of Food and Agriculture (CDFA), the California Exotic Pest Plant Council (CalEPPC), the U.C. Davis CalWeed Database, and CalFlora. The Science Team also obtained soils information from the Soil Survey of the Tahoe National Forest (USDA 1994), and the Soil Survey of Nevada County (Brittan 1993) to determine the presence of soils that are often associated with Redlist and Yellowlist plant taxa in the region.</p>
      <p>
Other sources that were consulted for information on Redlist and Yellowlist plants and sensitive ecosystems in Nevada County included the following regional and local natural resource reports: “Sierra Nevada Ecoregional Plan” (The Nature Conservancy 1999); “Important Natural Communities of Nevada County, California (INCA)” (Environment and Planning Associates 1998); the “Sierra Nevada Ecosystem Project (SNEP)” (1996). </p>
      <p>
All of the above-listed sources were reviewed to develop a matrix of the habitat associations of the Redlist and Yellowlist plant taxa in Nevada County (Appendix III).  For each rare plant taxa, this matrix indicates its Redlist or Yellowlist status and its documented occurrence in each of the 27 large-patch ecosystems that were mapped in the county. The Science Team did not perform any surveys for Redlist or Yellowlist plants as part of this project. However, incidental observations of some Yellowlist species were made during field surveys on public lands. </p>
      <h3 id="c2-vertebrate-diversity">
<i>Vertebrate Diversity </i></h3>
      <p>The Science Team compiled a list of the vertebrate species with known or potential occurrence in Nevada County from university and agency databases, museum records, published literature, and consultations with agency personnel and other local experts (Appendix IV). This list includes all vertebrate species that are known to occur in the county, including introduced species and extremely rare species (i.e., nonbreeding species with fewer than five documented occurrences in Nevada County).  It also includes a few animal species whose occurrence in the county is uncertain; they could occur here based on their known geographic range and habitat requirements, but there are apparently no documented records or voucher specimens for the county.</p>
      <p>
The Science Team consulted the following published sources for specific taxonomic groups: fishes (Moyle 1976, Moyle et al. 1995); amphibians and reptiles (Stebbins 1966, Verner and Boss 1980, Zeiner et al. 1990, Jennings and Hayes 1994); birds (Grinnell and Miller 1944, Remsen 1978, Verner and Boss 1980, Beedy and Granholm 1985, Zeiner et al. 1990, Gaines 1994, Williams 1997); mammals (Ingles 1965, Hall 1981, Verner and Boss 1980, Williams 1986, Zeiner et al. 1990). A complete list of the butterflies in Nevada County is available at:<br>
        <u><a href="www.npwre.usgs.gov/resource/distr/lepid/bflyusa/ca/300.htm"><font size="1" color="#666666">www.npwre.usgs.gov/resource/distr/lepid/bflyusa/ca/300.htm</font></a></u></p>
      <p>Questionable records of unusual or rare species were researched by examining specimens and collection records at the Museum of Vertebrate Zoology, UCB; the Wildlife Museum at UCD; and the Wildlife Museum at the University of Nevada, Reno. Data files maintained by Tahoe National Forest, and the Sierra Foothills Audubon Society were also reviewed for unpublished records of birds and mammals in Nevada County. </p>
      <h3 id="c2-redyellow-animals">
<i>Redlist and Yellowlist Animals</i></h3>
      <p>For this project, Redlist animals were defined as those species that are listed as  Threatened,  Endangered, or Candidates on the state and/or federal endangered species lists.  Yellowlist species include all other special-status animals that are included on lists of sensitive or special concern taxa that are maintained by federal agencies (i.e., National Marine Fisheries Service, USFWS, USFS, BLM) and/or state agencies (i.e., DFG, CDF).</p>
      <p>
A list of Redlist and Yellowlist animals with known or potential occurrence in Nevada County (Appendix V) was prepared using the same sources of information that are listed above (see “Vertebrate Diversity,” above).  In addition to these databases, published sources, museum collections, and local experts, primary information sources for compiling lists of Nevada County’s Redlist and Yellowlist animals were the California Department of Fish and Game’s Natural Diversity Data Base (CNDDB 2002a) and list of Special Animals (CNDDB 2001).</p>
      <p>
Appendix V includes information on the legal status, California distribution, habitats, and reasons for decline or concern for all Redlist and Yellowlist animal species with known or potential occurrence in Nevada County.  The Science Team did not perform any surveys for Redlist or Yellowlist animals as part of this project. However, incidental observations of some of these species were made during the field surveys on public lands. The draft list of Redlist and Yellowlist animals for Nevada County was peer-reviewed by the qualified fisheries and wildlife biologists identified in Appendix V.  When possible, the data contained in the draft list were also field-verified during the watershed surveys (see “Watershed Surveys,” below).</p>
      <h3 id="c2-whr">
<i>Wildlife Habitat Relationships</i></h3>
      <p>The Science Team compiled a “Nevada County Wildlife Habitat Relationships” (NCWHR) matrix to provide an overview summary of the occurrence of native fish, amphibians, reptiles, birds, and mammals in each of the county’s large-patch ecosystems (Appendix VI).  This matrix was compiled initially from the California WHR (CWHR) electronic database (Zeiner et al. 1990).  The CWHR database was designed for the state-wide analysis of wildlife habitat relationships. It provides a general, but incomplete, list of potential vertebrates in Nevada County and of their occurrence in specific large-patch ecosystems. The CWHR species list was updated according to the peer-reviewed vertebrate county species list that was compiled for this project (Appendix IV).</p>
      <p>
Only native animal species that are known to occur regularly in the county were included on the NCWHR matrix, and all exotic and extremely rare species (i.e., &lt;5 occurrences in the county) were excluded.  Species occurrence data for each of the large-patch ecosystems (including three elevation zones for Riverine and Lacustrine ecosystems) were entered into an electronic spreadsheet.  The initial CWHR species and habitat associations were refined in the NCWHR matrix based on documented observations of individual species in Nevada County and in nearby counties. Individual species were coded as “1” if they use a specific large-patch ecosystem for feeding, resting, or migration, but do not breed there.  Species were coded as “2” if they are year-round residents in a specific large-patch ecosystems, or if they have been documented breeding there in the county. Key assumptions of the NCWHR matrix coding were: </p>
      <ul type=square>
        <li>
 species were only coded for a specific NCWHR type if they occupy it for some significant portion of their life cycle (e.g., most amphibians are shown as only occurring in streams and other aquatic habitats, but not in adjacent conifer forests or upland habitats unless they are used for migration, hibernation, foraging, etc.).</li>
        <li>
 wildlife and habitat associations included in the matrix were coded at a broad, county-wide scale, so the matrix will usually predict a larger number of species occurring in a particular habitat patch than actually are present; </li>
        <li>
 coded wildlife habitat relations, especially forested habitats, represent a mix of successional stages including at least some late-successional stands (e.g., at least some trees &gt;24 inches dbh); if these habitat elements are absent, many predicted wildlife species may not be present;</li>
        <li>
 habitat areas must be sufficiently large to accommodate the requirements of species with large home ranges; such species may be absent from small or discontinuous patches of habitat.</li>
        <li>
The draft NCWHR matrix was reviewed by wildlife biologists with many years of professional experience observing wildlife habitat relationships in the Sierra Nevada, including DFG and USFS biologists. Members of the Science Team also reviewed the NCWHR matrix extensively in the field during the watershed surveys (see “Watershed Surveys,” below).  All suggested changes from outside reviewers and field surveyors were assessed and incorporated into the matrix if supported by direct observations, or based on other reliable sources such as published literature or museum voucher specimens.</li>
      </ul>
      <p>
The revised and corrected NCWHR matrix was used to develop the following additional data summaries for each of the 27 large-patch ecosystems in Nevada County, including the total number of potential: </p>
      <ul type=square>
        <li>
 vertebrate species (including all breeding and nonbreeding species); </li>
        <li>
 breeding (and resident) vertebrate species; and, </li>
        <li>
 Redlist and Yellowlist vertebrate species.</li>
      </ul>
      <h3 id="c2-invasive">
<i>Invasive, Non-Native Plants and Animals</i></h3>
      <p>The Science Team prepared a list of invasive, non-native plants known to occur in Nevada County. For the purposes of this Study, the term “Noxious Weed” is defined as invasive non-native species included on the weed lists of California Department of Food and Agriculture (CDFA) and the California Exotic Pest Plant Council (CalEPPC).  These agencies provide information on pest ratings, habitat preferences, and distribution of non-native, weedy species. Many other non-native plants are found in the County that are either too widespread to be considered by the agencies and organizations described above, or are not invasive.</p>
      <p>
Other sources of information on invasive, non-native plants in Nevada County include the electronic databases of CDFA, CalEPPC, and U.C. Davis websites that contain valuable information on the identification, propagation, and biological, mechanical, and chemical control of weeds. The Science Team also searched the electronic databases of the U.C. Berkeley Digital Library Project CalFlora Database (CalFlora 2002) and the U.C. Davis CalWeed database for Nevada County. The CalFlora database provided lists of documented occurrences of invasive and non-native plants in Nevada County from the major herbaria. Additionally, invasive non-native species observed during the field surveys were also noted and added to the lists for individual watersheds (see “Watershed Surveys,” below). </p>
      <p>
Observations of introduced animals such as bullfrogs, wild turkeys, European starlings, house sparrows, and wild pigs were recorded in field notes during the Watershed Surveys.</p>
      <h2 id="c2-gis">
<br>
        Geographic Information System (GIS) Mapping </h2>
      <h3 id="c2-gis-background"><i>Background</i></h3>
      <p>The Science Team used GIS-based technology to compile digital map information about Nevada County and to generate statistics summarizing the extent of the county’s physical and biological resources. A GIS system is a set of computerized maps that are linked to electronic databases. A GIS is composed of individual “layers,” or “data themes,” each representing a unique kind of mapped information (Zeiler 1999). A road layer data theme, for example, will contain a series of lines, each of which represents a road. For each road, an entry (row) will exist in a related database, and various database columns may describe the road’s name, length, surface type, and use levels.</p>
      <p>
Many people think of GIS simply as computer-generated maps. However, the real power of a GIS system is its ability to summarize the large and complex databases that underlie the computer-generated maps. GIS enabled the Science Team to calculate statistics about the physical and biological resources of Nevada County and to catalog specific attributes of its 100 mapped watersheds. For example, the GIS can rapidly calculate the number of acres of Foothill Hardwood Woodlands occurring on public land within 150 feet of the streams mapped by the U.S. Geological Service (i.e., 7.5-minute topographic maps) at both watershed and county-wide scales.</p>
      <p>
A GIS system is capable of producing maps with an almost infinite variety of data layers, but the accuracy of individual maps depends on the quality of the data that are entered into the system.  In order to create highly accurate maps and statistics about Nevada County, the Science Team started by acquiring and compiling the most current databases available from county, state, and federal agencies and non-government organizations.  Based on the initial GIS-based maps and data summaries, the Science Team then spent more than 1,600 hours of field time verifying that these maps are accurate for use in Nevada County (see “Watershed Surveys,” below).</p>
      <h3 id="c2-data-sources">
<i>Data Sources and Management</i></h3>
      <p>The Science Team assembled a set of GIS databases that were produced from extensive, recent mapping by state and federal agencies, the Nevada County Planning Department, local agencies, universities, research biologists, and scientific non-government organizations.  More than 200 individual databases were acquired and reviewed in this process (Appendix VII), and all of these are available on the Internet or from public agencies (most for free, but some at a cost). The data from these many different sources were available in a variety of electronic formats: digital images, digital elevation models, ArcView shapefiles, global positioning system points, and digital raster graphics (DRGs), among others. All data were converted to ARC/INFO coverages and grids to create a consistent format for summarizing and mapping data.  All imported GIS data were converted to a standard projection, “CA Albers,” that was developed by the State of California Stephen P. Teale Data Center GIS Lab. The CA Albers projection is the  standard projection for sharing data between state, federal and local agencies in California. </p>
      <p>
All GIS-based analyses were undertaken using data gathered for Nevada County.  However, some additional GIS data were also acquired for adjacent portions of the four counties surrounding Nevada County: Placer, Yuba and Sierra counties (California) and Washoe County (Nevada). Data were gathered for this larger area to verify the accuracy of data near the county line. Thus, some data from other counties were used to verify the accuracy of mapped information near the Nevada County line.</p>
      <h3 id="c2-screening">
<i>Screening and Selection of Data Themes</i></h3>
      <p>From the original 200+ databases that were acquired and screened, the SAC selected a subset of more than 40 of these to be compiled, evaluated, and summarized for this report (Appendix VIII). The major data themes that are summarized in this report focused on: large- and small-patch ecosystems, habitats and species occurrence, physical themes, and land use themes. A rigorous screening process was developed to eliminate data sets that were not valid for this study, based on inappropriate map scale at the time of digitizing, redundancy with other databases, incomplete coverage in any one of the elevation zones, and other factors. Appendix VIII lists all data themes that were used to compile maps and data summaries, GIS methods used, and the validation process for each data theme. </p>
      <h3 id="c2-gis-techniques">
<i>Overview of GIS-Based Techniques </i></h3>
      <p>Data can be stored in a GIS system as either vector (i.e., points, lines, and polygons), or “raster” images (grids) (Zeiler 1999). Vector data include features with definite locations, like “springs and seeps,” and are stored as points. Long narrow features, like streams, canals, utility corridors, and roads are stored as lines. Features that cover a defined region, like a patch of forest or chaparral, can be represented as polygons (areas of irregular shape defined by vector lines) or rasters (digital graph paper where each unique feature covers a set of cells). Complex data, with arbitrary boundaries, such as rainfall maps, also are stored as raster data sets. </p>
      <p>
<i>Vector (Line and Point) Methods</i></p>
      <p>Point location information (i.e., springs, seeps, and fens) and linear features (i.e., rivers, canals, and roads) are summarized as vectors. Vector data are composed of points with “real world” coordinates such as latitude/longitude that can be connected as “arcs” or lines (Zeiler 1999).  </p>
      <p>
Point features (e.g., springs and seeps, and mine shafts) were analyzed using the “point method.” A vector coverage, representing the watershed, was intersected with a point coverage representing the occurrences of a data theme (e.g., mine shafts). This produced a database where every point in the input theme was assigned to the watershed where it occurred. A database program was used to count all the points and to create a table summarizing the total number of points where each resource occurs in each watershed. </p>
      <p>
Line features (e.g., roads, canals, and creeks) were analyzed using the “line method.” Each line was assigned to a single watershed. In a database program, the total length of all lines in each watershed was summed and converted to units of miles.  This created a table summarizing the total number of miles of a theme in each watershed.  In some cases, the input lines were first clipped to a small portion of the watershed. For example, when calculating the number of road miles in the streamside zone by watershed, the input lines were first clipped to the streamside zone only. In this case, only road segments in the streamside zone were counted toward the “Roads in Streamside Zones” data theme. </p>
      <p>
<i>Raster Methods</i></p>
      <p>Continuous surfaces (e.g., digital representations of elevation contours) and polygons with defined areas (e.g., ecosystem polygons) were analyzed as rasters (Zeiler 1999). In a raster model, a digital piece of graph paper is established in a known map projection with a defined cell size.  A map projection is a way to show spherical information on a flat surface. Each cell in the graph is assigned a number that represents a feature (e.g., blue oak trees) in an associated database. If the cell size is set to 1 foot, hundreds of cells may represent a single tree. If the cell size is 1 acre, a single cell will represent many trees. The larger the cell size, the faster the computer runs, and the less precise are the results. The 30-meter cell size used in this analysis was determined to be the optimal size to capture all the spatial precision of the available data sets without compromising processing time.</p>
      <p>
Most data themes represented a single category of geographic information, such as the acreage of Urban areas or Croplands in the county . In the “area” method a single raster was created for each theme, where the value “1” indicated the presence of theme in a cell, and zero “0” indicated its absence. A program was written that stepped through each watershed and counted the total number of cells with a value of one. This created a table with the watershed number and the number of cells representing each theme. Since each cell was 30 meters on a side, a single cell represented 900 square meters. To derive total acres, the number of cells was multiplied by 900, divided by 10,000 (yielding hectares), and multiplied by 2.471 (the conversion factor from hectares to acres).  The area method was used to summarize the acreages of all large- and small-patch ecosystems, and for “NID Arable Lands,” “NID Irrigated Lands,” and for “Public/Private Lands” (Appendix VIII).</p>
      <h3 id="c2-ecosystem-themes">
<i>Ecosystem Data Themes </i></h3>
      <p>Ecosystem data themes tracked the distribution and acreage of large-patch ecosystems (e.g., Foothill Hardwood Woodlands, Ponderosa Pine Forest, and Montane Chaparral), and small-patch  ecosystems (e.g., McNab Cypress and Whitebark Pine Stands) in each watershed. The primary source of information on the extent of large-patch ecosystems was the Forest and Rangeland Assessment Program (FRAPP) of the California Department of Forestry. As part of its California Land Cover Mapping &amp; Monitoring Program, Second Statewide Cycle, FRAPP made a GIS-based coverage of Nevada County vegetation based on ecological modeling and satellite image analysis (LCMMP 1994-2002). The Science Team checked these data for errors on a per watershed basis, made minor corrections as necessary, and created unique layers for each large-patch ecosystem.</p>
      <p>
Small-patch ecosystems were mapped from NRCS soil maps (Brittan 1993) and field surveys on public lands and roads. Some small-patch ecosystems were mapped by a visual assessment of aerial photography.  Assigning real world coordinates to the photographs made this mapping more accurate. Aerial photos were transformed into the CA Albers projection, corrected for spatial errors introduced by topography, and spatially merged into seamless, digital orthophotograph quadrangles.  The corrected maps for each small-patch ecosystem were then electronically digitized onscreen from the orthophotographs into the final GIS layers.</p>
      <p>
Each of the large-patch ecosystems occurring in a specific watershed was counted, and this total count created a new data theme, “Number of Large-Patch Ecosystems per Watershed.” A program derived this range of values by examining each watershed and counting the number of unique cell values (greater than zero) from the NCWHR theme grid.  This count created a table with the number of large-patch ecosystems that occur in each watershed.  The number of Redlist and Yellowlist plants and animals documented in each large-patch ecosystem were summed from the NCWHR matrices (Appendices III and VI). This information was derived primarily from DFG’s Natural Diversity Data Base (CNDDB 2002a) and was represented in the GIS by point location data. </p>
      <h3 id="c2-other-themes">
<i>Other Data Themes</i></h3>
      <p>Many important Land Use data themes may influence the distribution and persistence of native plants and animals in the county. Examples of such data themes include: “Dams and Reservoirs,” “Development in Streamside Zones,” “NID Irrigated Lands,” and “Public and Private Lands.” These data themes were summarized as line, area, or mean values in the GIS. Data themes such as “Development in Streamside Zones” and “Contiguous Unimproved Lands” were processed using the “mean” method (Zeiler 1999).  Similar to the “area” method, a program was used that stepped through each watershed and examined all cells within it. Instead of summing those with a value of “1” the program summed all the values greater than zero, divided this sum by the number of cells, and produced a mean cell value for each watershed statistic. The “mean method” was used for all themes with a continuous surface of values, such “Parcel Size in Streamside Zones” (Appendix VIII).</p>
      <h3 id="c2-error-correction">
<i>Error Correction Processes</i></h3>
      <p>Accurate data are essential to produce valid GIS maps and analyses.  The Science Team used several error-correction processes due to the size and complexity of the original data sources.  The first process was a visual inspection to search for large-scale errors in all the computerized maps and summarized databases. Coarse errors, resulting from inaccurate data, were easily detected and corrected by overlaying the data on some form of physical geography, such as an earth surface model or satellite image to determine if mapped polygon boundaries were coincident. Errors identified through this process were corrected in the data tables or routines (programs) that generated the maps and statistics. </p>
      <p>
Fine-scale errors in GIS-based maps can only be detected with field work or by careful examination of aerial photographs (see “Watershed Surveys,” below). Most GIS datasets are not absolutely accurate, and their relative accuracy must be weighed against their intended use. Usually the scale of the analysis determines the level of precision that will be required. When an engineer is designing a pipeline alignment, accuracies within an inch may be called for. However, when performing analysis at a watershed (e.g., 5,000 to 12,000 acres), county, or statewide scale, a mapping accuracy of 100 feet may be sufficient. The units of analysis in this study were watersheds that ranged from 150 acres to 12,695 acres in extent. Almost all analyses were conducted using raster representations of the map data with a 30-meter cell size. Each cell equals approximately 1/5th acre (0.22 acres). Spatial errors less than 100 feet were not corrected because they were smaller than a single analytical unit, or cell. </p>
      <p>
The GIS data themes used in this report are all based on government and scientific maps and databases of varying age. These had to be validated in Nevada County before they could be used with confidence in this analysis. There will never be sufficient resources to field-check each line, point, and polygon for every data theme. Recognizing these limitations, the Science Team surveyed a subset of the data themes used in a subset of watersheds. For example, the GIS produced a map showing all the watersheds where serpentine soils are abundant.  The existence of this theme in the locations suggested was tested in the field from public lands and roads (see “Watershed Surveys,” below). </p>
      <h2 id="c2-watershed-surveys">
<b><br>
        </b>Watershed Surveys</h2>
      <p>Science Team members conducted countywide field surveys from May through October 2001. Survey objectives were to:</p>
      <ul type=square>
        <li>
 verify the accuracy of the selected data themes on a watershed-scale throughout Nevada County; </li>
        <li>
 perform reconnaissance-level field surveys of Nevada County’s 100 watersheds; </li>
        <li>
 evaluate the presence or absence of various large- and small-patch ecosystems that occur in individual watersheds as well as the presence of sparsely-vegetated habitats, such as Lacustrine (standing water), Riverine (flowing water), cliff habitats, rock outcrops, talus slopes, or other rocky or barren manmade habitats (e.g., hydraulic diggings or surface mines); and, </li>
        <li>
 assess the extent and condition of the individual ecosystem types on public lands.</li>
      </ul>
      <p>
Each of Nevada County’s 100 watersheds was assigned to one of two survey teams (each containing an experienced, local botanist and wildlife biologist) based on amounts of previous knowledge of a particular area and/or prior survey experience in a watershed. Approximately 16 person-hours were spent per watershed. All field survey work was done from public roads, or on public lands, which constitute about 1/3 of the county’s land area. Public or private road status was determined through the use of GIS-generated road maps provided by the County of Nevada and by the use of USFS ownership and topographical maps. Public lands include USFS, BLM, state or county parks, fire and sanitation districts, and city-owned lands. In addition, some privately-owned parcels were surveyed after written requests were received from the property owners. </p>
      <p>
As discussed in the following sections, the Science Team verified the GIS information using both pre-field (office verification) and field surveys (on-the-ground verification). Time and access limitations did not permit all watersheds to be surveyed with equal intensity or precision, and even many well-roaded watersheds were not surveyed completely.  Since the watershed surveys were conducted at a reconnaissance-level, they were not intended to be comprehensive or site-specific.  This type of inventory is appropriate and adequate for the identified survey objectives.</p>
      <h3 id="c2-office-verification">
<i>Office Verification of GIS Data Themes</i></h3>
      <p>The Science Team obtained digitized aerial photographs from two sources: USFS and the County of Nevada. USFS photographs (1:15,840 scale, flown in July/August 2000) of Tahoe National Forest lands covered a major portion of Nevada County (both public and private) in Elevation Zones 3 and 4. Areas not covered by USFS aerial photographs in Elevation Zones 1, 2, and 4 were commissioned and purchased by the County. They were flown in September, October and early November 2000 at a scale of 1:13,305. Most of the GIS data themes were verified in the office using these aerial photographs, especially the NCWHR vegetation map (a watershed map showing all large-patch ecosystems).  Individual map layers display the extent and distribution of major large-patch ecosystems such as Foothill Hardwood Woodlands, Ponderosa Pine Forest, or Montane Meadows present in a watershed.</p>
      <p>
The Science Team made direct comparisons of the aerial photographs and mapped vegetation themes to determine if the species composition, extent, and distribution were accurate. All mapping themes were tested for accuracy in at least three map locations, and findings were documented on the individual maps. Any pattern of inaccuracy was communicated to GIS mapping specialists so that corrections could be made and new maps generated and reevaluated. This method was applied to all watershed maps and the various theme types for all 100 watersheds surveyed. For example, areas initially mapped as Annual Grasslands often were found to contain sparse stands of oaks and other hardwoods, and they were later reclassified in the field as Foothill Hardwood Woodlands on the GIS maps. </p>
      <p>
A number of GIS data themes and maps pertaining to agriculture and residential development and their infrastructure were included in the mapping process. These included the location and extent of Urban and agricultural areas including Vineyards, Orchards, and Croplands in the county. Separate map layers were created for canals and irrigation canals, jurisdictional dams, lakes and reservoirs, and transportation and utility corridors. The Science Team used the aerial photographs to verify the accuracy of these themes by determining if any major errors or omissions existed in the mapped themes of these data sets.</p>
      <p>
Generally, all ecosystem data themes had distinctive signatures on the photographs and they were easily verified. Additional themes that were primarily evaluated by inspection of aerial photographs included: the amounts  of road miles and developed parcels that occur within stream zones (defined as approximately 150 feet on either side of the stream channel [Kondolf et al. 1996]); large areas of roadless land (Roadless Areas); and other unimproved lands.   Mapping themes that were in densely forested regions were reevaluated in the field because specific signatures were difficult to observe on aerial photographs of these habitats. </p>
      <p>
The Science Team reviewed other sources in the office prior to conducting field surveys including: the Natural Resource Conservation Service and Tahoe National Forest soil surveys; USDA Forest Service topographical maps; DFG’s California Natural Diversity Data Base (CNDDB 2002a); published references; and preliminary lists of plants and animals that were prepared specifically for this project (Appendices I, II, III, IV, V, and VI).</p>
      <p>
Published Nevada County soil surveys were used to locate: 1) potential wetlands or other water-dependent plant communities (by cross referencing the mapped wet subsoil types of the various soil series and mapped alluvial soils from the aerial photographs); 2) potential rare plant habitats on public lands (by locating tracts of serpentine and gabbrodiorite-derived soils types similar to types which support rare plants at other locations in Nevada County); 3) areas with potential concentrations of native forbs, grasses, or potential special-status plants (by including on the field survey routes mapped areas of rock land and other rocky complexes or soil types similar to those on which there have been other known rare or sensitive plant occurrences).</p>
      <p>
Aerial photographs were used to help establish field survey routes in addition to their use for office verification of the GIS-based vegetation maps. Visible areas containing sensitive vegetation communities, such as wet meadows, riparian and marsh habitats, or extensive tracts of quaking aspen or black cottonwood, were added to the survey routes. Potential field survey routes were plotted on U.S. Geological Survey topographical maps (7.5’), based on information obtained from aerial photographs, soils surveys, and other sources. These routes were generally located along major, public road thoroughfares and were plotted on the maps. These checkpoints included a wide range of GIS data themes to incorporate into the survey (e.g., locations of various wetlands, riparian areas, tracts of Serpentine or Gabbrodiorite Soils).</p>
      <p>
Topographic maps helped to establish positions along ridgelines and hilltops where expansive views of the watersheds could be accessed for data collection. They also depict low-lying areas or bottomlands as well as gentle-gradient portions of streams where depositional accumulations often occur. These areas frequently contain valley oak woodlands, wetlands, or high-quality riparian habitats. </p>
      <h3 id="c2-field-verification">
<i>Field Verification of GIS Data Themes </i></h3>
      <p>The Science Team performed field surveys to verify particular mapping themes that could not be verified in the office, such as the presence of mature Montane Hardwood forest, late-successional (see Results, “Small-Patch Ecosystems” for the definition used to characterize “Late-Successional Forest”), and many small-patch ecosystems. Other field-verified data themes included canals and roads in forested areas where they were not visible on aerial photographs because of dense forest cover. These data themes were substantiated in the office in some locations and in the field using GPS units in others. Since these themes needed only to be tested in three locations, all selected sites were on public roads that offered good views. </p>
      <p>
Systematic surveys were not conducted for mine shafts and surface mines, primarily because the vast majority are located on private lands and were inaccessible or difficult to find. A very small number of mines were encountered and documented on public lands, primarily in BLM ownership. </p>
      <p>
Total stream distances in a watershed were calculated as the summed length of every stream in a watershed and the terminus (or point of origin) of each individual stream. The stream terminus was determined and verified by the presence of the first signs of scouring or a defined stream channel. For expediency, stream origin points visible from public roads were selected to verify theme accuracy.</p>
      <h2 id="c2-feedback"><b>
<br>
        </b>Feedback and Data Correction</h2>
      <p>Data summaries and maps for each of Nevada County’s 100 watersheds are provided in Appendix IX.  All of these maps were carefully reviewed in the field, and suggested changes were made to the underlying GIS databases. In a few cases when data were found to be highly inaccurate, the entire databases were rejected for use in this analysis. When possible, new, more accurate databases replaced the originals (see Appendices VII and VIII).  For other databases, no suitable substitutes were available, and they were dropped from the final analysis (e.g., “Limestone Substrate” layer). Replacement databases were only used in the analysis when the Science Team could verify their accuracy based on published data, or when the new data came directly from the Watershed Surveys. </p>
      <p>
<b><i>Note:</i></b> Every effort was made to ensure accuracy of all GIS layers used. All known errors were corrected.  Some layers were created late in the science process using aerial photo interpretation only. These layers, including foothill riparian woodlands and fresh emergent wetlands, were not subject to field validation. 100% accuracy of all layers is not implied or guaranteed. None of these datasets should be used in lieu of project level biological inventories.</p>
      <p><br>
      </p>
`;

export default function Page() {
  return (
    <article className="report-content prose prose-sm prose-slate max-w-none
      prose-headings:font-bold prose-h1:text-xl prose-h2:text-base prose-h3:text-sm
      prose-a:text-[#4a5722] prose-a:no-underline hover:prose-a:text-[#cc6600]
      prose-img:my-2">
      <div dangerouslySetInnerHTML={{ __html: html }} />
    </article>
  );
}
